image: node:latest

stages:
  - build
  - run
  #- test

# Job's name
Build project:
  # Define stage
  stage: build
  before_script:
    - cd iug
  # What to run on the job.
  script:
    - npm install
  artifacts:
    paths:
      - node_modules

Lint:
  stage: run
  before_script:
    - cd iug
    - npm install
  script:
    - npm run lint:fix
    #- node test.js
  artifacts:
    paths:
      - node_modules/

#Test project:
 # stage: test
  #before_script:
    #- cd iug
    #- npm install
  #script:
   # - npm test
    #- node test.js
  #artifacts:
   # paths:
    #  - node_modules/
